name: Caller Wfl
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version for current release'
        required: true
        type: string
env:
  USERNAME: "VishnuPratapBankii"
  TOKEN: ${{secrets.USER_TOKEN}}

jobs:
  
  call-the-deploy-wfl:
    uses: VishnuPratapBanki/environment_testing/.github/workflows/called.yaml@main
    permissions:
      contents: write
    with:
      version: ${{inputs.version}}
#    secrets:
#      token: ${{secrets.MYTOKEN}}

