name: Caller Wfl
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version for current release'
        required: true
        type: string
env:
  USERNAME: "VishnuPratapBankii"
  TOKEN: ${{secrets.MYTOKEN}}

jobs:
  
  call-the-deploy-wfl:
    uses: VishnuPratapBanki/environment_testing/.github/workflows/called.yaml@main
    with:
      version: ${{inputs.version}}
    secrets:
      TOKEN: ${{secrets.MYTOKEN}}

